#!/bin/bash

if [[ -z $SYSROOT ]]; then
	echo "ERROR: You have to set SYSROOT to use cross-emerge-ng!"
	exit 1
fi

# Get host triplet from build platform in /
export CBUILD=$(portageq envvar CHOST)

# Switch to host platform in SYSROOT
export ROOT="${SYSROOT}"
export PORTAGE_CONFIGROOT="${SYSROOT}"

if [[ -z $DONT_WRAP_COMPILERS ]]; then
	export CFLAGS="--sysroot ${SYSROOT} $(portageq envvar CFLAGS)"
	export CXXFLAGS="--sysroot ${SYSROOT} $(portageq envvar CXXFLAGS)"
	export CPPFLAGS="--sysroot ${SYSROOT} $(portageq envvar CPPFLAGS)"
	export LDFLAGS="--sysroot ${SYSROOT} $(portageq envvar LDFLAGS)"
fi

exec emerge "$@"
