#!/bin/bash

if [[ -z $SYSROOT ]]; then
	echo "ERROR: You have to set SYSROOT to use cross-emerge-ng!"
	exit 1
fi

# Get triplet from build machine in /
export CBUILD=$(portageq envvar CHOST)

# Switch to host machine in SYSROOT
export ROOT="${SYSROOT}"
export PORTAGE_CONFIGROOT="${SYSROOT}"

if [[ -z $DONT_WRAP_COMPILERS ]]; then
        export CC="__PREFIX__/lib/crossdev/bin/sysroot-gcc"
        export CXX="__PREFIX__/lib/crossdev/bin/sysroot-g++"
fi

exec emerge --crosscompile "$@"
