#!/bin/bash

if [[ -z ${CHOST} || -z ${SYSROOT} ]]; then
	echo "ERROR: You have to set CHOST and SYSROOT to use cross compiler wrappers!"
	echo "You should use cross-emerge-ng which sets this."
	exit 1
fi

exec "${CHOST}-${0##*-}" --sysroot "${SYSROOT}" "$@"
